name: nilmtk-device
dependencies:
  - Click==7.0
  - Flask==1.1.1
  - gunicorn==19.9.0
  - itsdangerous==1.1.0
  - Jinja2==2.10.1
  - MarkupSafe==1.1.1
  - pytz==2019.1
  - six==1.12.0
  - python=3.6
  - Cython>=0.27.3
  - bottleneck>=1.2.1
  - numpy>=1.13.3
  - numexpr>=2.6.4
  - pytables
  - pandas>=0.24.2
  - matplotlib>=2.2.0
  - networkx==2.1
  - scipy>=1.0.0
  - scikit-learn>=0.21.2
  - jupyter
  - ipython
  - ipykernel
  - six
  - future
  - nose
  - coverage
  - pip
  - psycopg2
  - pip: # Install packages which are not in conda. Install these using pip:
      - coveralls
      - aniso8601==7.0.0
      - Flask-RESTful==0.3.7
      - Werkzeug==0.15.5
      - https://github.com/hmmlearn/hmmlearn/archive/de0546eaab01ce11c9f8481a9e8eaf7526adc113.zip#egg=hmmlearn
      - https://github.com/nilmtk/nilm_metadata/archive/master.zip#egg=nilm_metadata
      - https://github.com/nilmtk/nilmtk/archive/master.zip#egg=nilmtk
